# --- Parametrs for the Local Costmap

local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  static_map: false  
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05