base_frame: base_link
map_frame: map
odom_frame: odom
map_update_interval: 5.0 # [sec] elapsed
maxRange: 4.5 # [m] scan range
linearUpdate: 0.125 # [m] moved
angularUpdate: 0.125 # [rad] rotated
temporalUpdate: 2.0 # [sec] elapsed
minimum_score: 0.25