# this is the training trajectory in a clockwise fashion
# basically, it's a diamond shape
# waypoints to travel
trajectory:
  # lower right vertex
  - x: 1.5 # [m]
    y: 0.0 # [m]
    theta: 0.0 # [rad]
  # upper left vertex
  - x: -1.5 # [m]
    y: 4.0 # [m]
    theta: 0.0 # [rad]
  # upper right vertex
  - x: 1.5 # [m]
    y: 4.0 # [m]
    theta: 1.57 # [rad]
  # lower left vertex
  - x: -1.5 # [m]
    y: 0.0 # [m]
    theta: 0.0 # [rad]